dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: vijayasankarn-github
    token:
      secure: irnH2LKTUs+udzCG885ape7Rafgo3KEVwKD25U0iqiRorRmlQXF0xeMmMgeIAnC5veZhuhAjKCxK3caj/YBhLpnJ5Yp8ukB/wOlFqh50vkT7rcUaNmNJDzIl9mZ9VR3Ab4jfPOae1paQa8mwKJYq1HnpCVYZtf9xPncGydPOA9+FX9mBKopV+x3RsB95U4WnQRq1tMIMxmwjnHnF7uG1g8Vgrud9/nylGC632WRbptva2rUpcJFDQm/2Rsg/i0ya0ZZQsQpHS1EzwRP7G3cDPRXsVzFH8n69BoQk5GZqYtIbOO812H7PGFKfsV0kRRKnKWKRfVQfXbBJzeHYQtLk9aIV851MqjCcd5qEaEWckgfAtu2t8rfMMUMkO/kQPriMSTSL4lNoAlAYL2mubSbmmvzGPi2vd6r5OrnDn0Mdm4X/HgskeWn+J7sBRFn7J4OAphCrcX/IXSa7GqI3hopPbl3KGVHHbwQLZP6sMBwasffQE0fG+e2j4h8TJjlGKyH/saW7KcMpAbtjAq8dyMJd6PZFaF92GrSjPu8MQEj6h/Dxo+0fuKJ2iHmTUf65eNoFrlZylQofqWKr536w3rSZZhraPkykwcFbvpUXOV/OY2H1USFMUGgGTj0WotJ+BU5sG3Kud/WnSb2AcMQ+/mMsnBLr0Omr+WE+9Twvye5l21g=
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"